#!/usr/bin/env node

const commandLineArgs = require('command-line-args');
const getUsage = require('command-line-usage');

const menu = require('./src/Model/Menu');
const Args = require('./src/Model/Args');

const ContentController = require('./src/Controller/ContentController');

let args = new Args(commandLineArgs(menu[1]['optionList']));

if (args.shouldShowHelp()) {
    console.log(getUsage(menu));
} else {
    console.log('\nStarting Site Content');
    let contentController = new ContentController(args);
    contentController.start().then();
}